### ISSUE TITLE
Can't develop on Windows 10 as Electron Window is not opening

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modv-3#127]
When starting the dev env using `yarn run electron:server`, the screen get stuck with this message:

```
 INFO  Launching Electron...
```

But it will never launch.

What works are using the release from GitHub or to build and then run the executable. 

I also tried the recommendations from https://github.com/electron-userland/electron-prebuilt-compile/issues/36 without any luck.

**Comment by TimPietrusky** [comment]
It looks like that those lines in `src/background,js` are the problem:

```
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    // Devtools extensions are broken in Electron 6.0.0 and greater
    // See https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/378 for more info
    // Electron will not launch with Devtools extensions installed on Windows 10 with dark mode
    // If you are not using Windows 10 dark mode, you may uncomment these lines
    // In addition, if the linked issue is closed, you can upgrade electron and uncomment these lines
    try {
      await installVueDevtools();
    } catch (e) {
      console.error("Vue Devtools failed to install:", e.toString());
    }
  }
```

Thanks to @2xAA for the hint, as when those lines are removed, Electron starts.

**Comment by 2xAA** [comment]
Apparently Electron 8.2.5 fixes this devtools issue, according to https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/378#issuecomment-630901784 .

We should remove the following code block until we can update `vue-cli-plugin-electron-builder` to a version which is not beta and that supports a newer version of `electron-builder` which in-turn supports Electron 8.2.5.

https://github.com/vcync/modv-3/blob/d9506b72102220b1c7920f1db7e1a8c8e5406f44/src/background.js#L323-L335
