### ISSUE TITLE
Sound input visualization and settings

### ISSUE THREAD

**Issue by LimeLimeW** [vcync/modv-3#130]
Add a gain bar/FFT bars to visualize the current audio input and the possibility to set the audio reactivity on certain frequencies.

**Comment by 2xAA** [comment]
Great feature, totally agree about the gain being visualised.

modV uses meyda to get specific audio features and doesn't present the FFT directly. https://meyda.js.org/

This is a list of the feature values that modV consumes:
https://jsbin.com/movezix/15/edit?output

A few questions:

Are you requesting FFT as another input here, or just to visualise the incoming audio signal to modV?

Where do we envision this to live right now? My preference would be in the status bar.

If this should be built with the new layout, maybe this should be part of a project here on GitHub?

**Comment by LimeLimeW** [comment]
The idea is to visualise the incoming audio signal to modV and select for example which frequencies we'd like to use. We could put the FFT bars on the input config tab, and have selectors (two arrows/lines) to surround the desired frequencies. 
A project would be good if we plan to do a total revamp of the UI with new functionalities.

**Comment by 2xAA** [comment]
Ah cool. This sounds like two features I think?

One feature to visualise the current state of Meyda's audio features, the gain and the FFT.

The other to allow frequency grouping and using the grouped frequencies as an input source to assign to a module's control.

If so, let's proceed by splitting this up :)

**Comment by 2xAA** [comment]
@Merristasis if you have a view on this, please let me know. Otherwise I will go ahead and split this into two issues

**Comment by LimeLimeW** [comment]
@2xAA Sorry I didn't saw your comment! 
Yes this looks good to me! Go ahead!

**Comment by 2xAA** [comment]
@Merristasis hopefully these issues describe the features well enough?
If so we can close this.

https://github.com/vcync/modv-3/issues/176
https://github.com/vcync/modv-3/issues/177

**Comment by LimeLimeW** [comment]
Yup we're good
