### ISSUE TITLE
Reopen a panel that was closed

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modv-3#132]
It's possible to close a panel, but how can I reopen it?

# How to reproduce
* Click on any panel
* Hit the `delete` key
* See that the panel is gone

# Ideas
* Use `ctrl + z` to undo the panel close?
* Use `View` or `Window` to reopen a panel

**Comment by 2xAA** [comment]
We need to find out how we programmatically open and close panels with Golden Layout.

I have a basic version of this working with the Module Properties panel (found in App.vue), but it's quite naive in implementation.

**Comment by 2xAA** [comment]
Hey @TimPietrusky,

I can't reproduce this on macOS or Windows. Untested on Linux.
Are you able to screen-record the issue?

Thanks.

**Comment by TimPietrusky** [comment]
@2xAA are you sure this comment belongs to this ticket?

**Comment by 2xAA** [comment]
@TimPietrusky Yes. I can't close a panel with the steps you outlined

**Comment by TimPietrusky** [comment]
@2xAA I have to test this again on Windows as on macOS it's not working. 

But what you can do is to close the module-panel using the `x` in the top right. After that you can't see the properties of a module anymore.

**Comment by 2xAA** [comment]
@TimPietrusky Any objections on disabling this entirely?
Right now I don't think it's beneficial to close any part of the layout.

I'd also want to disable the "maximise" buttons as they don't seem that useful.

**Comment by TimPietrusky** [comment]
> Any objections on disabling this entirely?

Please disable it!

> I'd also want to disable the "maximise" buttons as they don't seem that useful.

I think so too, it's only confusing if you do it right now.
