### ISSUE TITLE
Change the name of the master-branch

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modv-3#136]
Because of the relation to master/slave, we should change the name of the master branch to something else, maybe `main` or `latest`.

**Comment by 2xAA** [comment]
I agree. `main` works for me.

`latest` may cause confusion in terms of "download out latest release from GitHub".

Do you know if GitHub are gonna change this as default? I think they should.

**Comment by TimPietrusky** [comment]
Then I will change it to `main`. 

> Do you know if GitHub are gonna change this as default? I think they should.

People are demanding it, but I haven't seen an official statement yet.

**Comment by TimPietrusky** [comment]
Followed the steps provided at https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

```
git checkout master
git pull origin master
git branch -m master main
git push -u origin main
```

* Update the base branch to be `main`
* Update the branch protection to use `main`

For me it looks like that TravisCI will automatically use the base branch, but I'm not 100% sure about this. @2xAA can we somehow check this? I guess with the next release that is created out of `main` we will see. 

## Local clones

Execute the following to also use `main`:

```
git checkout master
git pull origin master
git branch -m master main
git fetch
git branch --unset-upstream
git branch -u origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

@2xAA can you please try this? 

If everything is fine we can get rid of `master`.

**Comment by 2xAA** [comment]
@TimPietrusky travis is set to watch any branch with tags for building right now.

And the local clones seems to work for me!
Let's axe `master`.

Thanks!

**Comment by TimPietrusky** [comment]
<img width="348" alt="Screenshot 2020-06-15 at 22 49 04" src="https://user-images.githubusercontent.com/492378/84704654-739fee80-af5a-11ea-8ca9-dd1524149f50.png">
