### ISSUE TITLE
Create an info view panel

### ISSUE THREAD

**Issue by 2xAA** [vcync/modv-3#166]
Ableton has an info panel which provides the user contextual help by hovering or focusing an element within Ableton.

This feature could be extremely useful within modV to demystify the usage of some features.  

![Screenshot 2020-06-17 at 23 10 13](https://user-images.githubusercontent.com/554219/84955763-b9da8680-b0ef-11ea-821e-a15225b1885f.png)

~~Another approach could be to implement a global search, though this is only really useful when you know what you are looking for and not a modV novice.~~

**Comment by TimPietrusky** [comment]
I think the `global search` should go into it's own issue as you already outlined that it would be useful for an experienced modV user that just wants to find the one specific thing. 

For everyone else, I think the `info panel` is super helpful, also to make up terms and be able to talk with others about the same thing using the same words.

**Comment by 2xAA** [comment]
Okay great. Let's split this!
