### ISSUE TITLE
Filesystem module loading

### ISSUE THREAD

**Issue by 2xAA** [vcync/modv-3#83]
Implement the ability to load modV modules from the filesystem and sending that code to the Worker, allowing dependencies to be automatically installed.

**Comment by TimPietrusky** [comment]
I would love to have hot-reload of modules, so if the underlying code is changing, the module in modV is also updating, even when it's already added to a group and I changed some parameters. As this would allow debugging and "playing" with code. 

@2xAA Should this go into a new issue?

**Comment by 2xAA** [comment]
HMR should be possible. It would be custom and not handled by webpack as this needs to run in production, but that shouldn't be an issue.

I'm currently stuck with some webpack module bundling error locally. It used to work in modV 2's media manager but doesn't here.

Once I get that sorted I should be ready to take a look at hot reloading.

I think we should create a new issue to track this though.

**Comment by 2xAA** [comment]
Seem to have fixed the webpack issue. I'm now dealing with a race condition where the media manager is sending messages to the renderer process without modV being ready.

I'll fix this with a message from modV to the background process to tell the media manager (and rest of the app?) that we're ready to receive messages.

**Comment by 2xAA** [comment]
Closed in #141.

**Comment by TimPietrusky** [comment]
Does this mean that the modules from modV 2 should work in modV 3? 

Edit: The differences will be seen in https://github.com/vcync/modv-3/issues/143

**Comment by 2xAA** [comment]
Shader and ISF modules should work.

2D modules however have an API change.
I'll document this in #143.
